### ISSUE TITLE
Windows 10 - JRE6 - Main thread dies due to Java7 compiled com.xeiam.xchange library

### ISSUE THREAD

**Issue by boutcher** [langerhans/multidoge#60]
When starting up, I see this in the logs, and then nothing (if the main thread dies, I can understand why)

07:08:24.907 [main] DEBUG o.m.v.swing.ColorAndFontConstants - labelBackground = 240 240 240
07:08:24.907 [main] DEBUG o.m.v.swing.ColorAndFontConstants - labelForeground = 0 0 0
07:08:24.909 [main] INFO  o.m.ApplicationDataDirectoryLocator - Application data directory.1 = 'C:\Users\James\AppData\Roaming\MultiDoge'
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/xeiam/xchange/exceptions/ExchangeException : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at org.multibit.viewsystem.swing.MultiBitFrame.<init>(MultiBitFrame.java:290)
        at org.multibit.MultiBit.main(MultiBit.java:239)
        at org.multibit.MultiBitInExecutableJar.main(MultiBitInExecutableJar.java:98)

**Comment by boutcher** [comment]
I'm sure this is due to Java 6 (only) being on this Windows 10 box I've used primarily for mining... I'm updating now. 

(But, I'm sure there are others who don't know how to look in a log and update Java -- so it may be useful to detect the version and throw up an error message telling them what to do if they encounter this problem, instead of the main thread dying)

**Comment by boutcher** [comment]
And did confirm, once Java 8 was installed, Multidoge launches fine.

**Comment by langerhans** [comment]
Yeah you're right. It requires Java 7 minimum. Normally the installer should check this requirement. Did you use that or ran the jar directly?

**Comment by boutcher** [comment]
I'm pretty sure I ran the installer, but to be honest, I'm not completely sure. Want me to recreate?
