### ISSUE TITLE
Is there a way to restore an old .wallet file?

### ISSUE THREAD

**Issue by Evo-Crypto** [langerhans/multidoge#90]
Hello i found an old .wallet file on my old USB-Drive. 
I don't have any .info file or backup file, just the .wallet file.
Importing into the multidoge wallet doesn't work. Is there a way to find the Private key or the adress to even check if i have ballance on this Wallet?

**Comment by AfzalivE** [comment]
I just did this. You can download Dogecoin-qt (Dogecoin core), copy the wallet.dat file to the location used by Dogecoin-qt, then start the app. 

It should show the unconfirmed balance and then you can go to the "Much receive" tab, open up Help > Debug window > Console and type `dumpprivkey <receive address>` for each address. Put all the outputs in a `doge-private-keys.key` file (each key separated by a new line) like this:

```
key1_goes_here
key2_goes_here
```

Then import this key file in MultiDoge. It will recognize all the keys.

Unfortunately, synchonizing is going to be a significant amount of download. If you don't want to download, you can use Exodus and use the "move funds" option, paste each private key there.

But it sweeps those addresses to incurs transaction fees.

**Comment by Evo-Crypto** [comment]
Thank you for your answer! But i don't have a "wallet.dat" file, i only have a "multidoge.wallet" file from Multidoge. Is there a way to convert it to an .dat file, so i can try this?

**Comment by SSouper** [comment]
i have the same issue, trying to open a old .wallet file errors out with com.google.dogecoin.store.UnreadableWalletException Could not read wallet. i dont have the .info file

**Comment by chris-hjelmfelt** [comment]
If you have a backup of .wallet you don't use the import tool. Did you try File-> Open Wallet and then choose the .wallet file you want to restore?

**Comment by Evo-Crypto** [comment]
Yes i tried this and got an error.
The Error sayes: "com.google.dogecoin.store.UnreadableWalletException Could not read wallet"

**Comment by chris-hjelmfelt** [comment]
Could your wallet backup file have gotten damaged? That's kind of what it sounds like to me.

**Comment by Evo-Crypto** [comment]
Could be yeah. Its an 6 year old Wallet and got moved through 3 PCs over the time. Sadly i only have the ".Wallet" file and not more.

**Comment by chris-hjelmfelt** [comment]
Yeah I had a bunch of files along with the .wallet file. I bet it doesn't know how to restore with only that one piece, It might be worth holding onto. If you think you have a bunch of coins maybe you would eventually find someone who had the knowledge to reverse engineer enough to see if the private keys are in that file. I don't know enough to be able to tell.

**Comment by Evo-Crypto** [comment]
Thanks for your answers! I will definitely hold on to it :)

**Comment by chris-hjelmfelt** [comment]
I found this article about .wallet files:
https://fileinfo.com/extension/wallet
It looks like there is a tool for extracting info from a Multibit wallet which uses the .wallet extension as well so there's a chance it might work. It does take some technical knowledge, but if you are really determined, or have a friend who can help, this might be a way to get at your keys:
https://github.com/Multibit-Legacy/read-multibit-wallet-file
Good Luck!

**Comment by btc2dogecom** [comment]
> Thanks for your answers! I will definitely hold on to it :)

you wallet file is corrupted maybe. putting it on the USD stick is easy get damage. we may help decrypt it if you have password of it. but chance is low.
www.btc2doge.com

**Comment by btc2dogecom** [comment]
> i have the same issue, trying to open a old .wallet file errors out with com.google.dogecoin.store.UnreadableWalletException Could not read wallet. i dont have the .info file

conact us. we may help decrypt the wallet if you have password. although the chance is low. how much doge u hold on that wallet?
www.btc2doge.com

**Comment by SSouper** [comment]
> > i have the same issue, trying to open a old .wallet file errors out with com.google.dogecoin.store.UnreadableWalletException Could not read wallet. i dont have the .info file
> 
> conact us. we may help decrypt the wallet if you have password. although the chance is low. how much doge u hold on that wallet?
> [www.btc2doge.com](http://www.btc2doge.com)

nice scam, how many people fall for it?

**Comment by btc2dogecom** [comment]
> > > i have the same issue, trying to open a old .wallet file errors out with com.google.dogecoin.store.UnreadableWalletException Could not read wallet. i dont have the .info file
> > 
> > 
> > conact us. we may help decrypt the wallet if you have password. although the chance is low. how much doge u hold on that wallet?
> > [www.btc2doge.com](http://www.btc2doge.com)
> 
> nice scam, how many people fall for it?

yes, many. millions people i guess. i planned all things, i developed multidoge and let all you guys locked and lose coins. yeah. i'm the breaking bad. 🥇 so please be scammed by me ! i beg you. 1 doge is ok. lol

**Comment by SSouper** [comment]
> > > > i have the same issue, trying to open a old .wallet file errors out with com.google.dogecoin.store.UnreadableWalletException Could not read wallet. i dont have the .info file
> > > 
> > > 
> > > conact us. we may help decrypt the wallet if you have password. although the chance is low. how much doge u hold on that wallet?
> > > [www.btc2doge.com](http://www.btc2doge.com)
> > 
> > 
> > nice scam, how many people fall for it?
> 
> yes, many. millions people i guess. i planned all things, i developed multidoge and let all you guys locked and lose coins. yeah. i'm the breaking bad. 🥇 so please be scammed by me ! i beg you. 1 doge is ok. lol

pretending to have developed multidoge now? cmon, your join date and everything is visible on your GitHub profile.

**Comment by armour248** [comment]
I'm an idiot. But when I do "npm install -g mbexport" I get the following...

npm ERR! code EEXIST
npm ERR! path C:\Users\xxxxx\AppData\Roaming\npm\node_modules\mbexport\build\mbexport
npm ERR! dest C:\Users\xxxxx\AppData\Roaming\npm\mbexport.cmd
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\xxxxxs\AppData\Roaming\npm\node_modules\mbexport\build\mbexport' -> 'C:\Users\xxxxx\AppData\Roaming\npm\mbexport.cmd'
npm ERR! File exists: C:\Users\xxxxx\AppData\Roaming\npm\mbexport.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxx\AppData\Roaming\npm-cache\_logs\2021-07-14T21_07_50_089Z-debug.log


and when I just go to a command prompt and try mbexport I get....

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\xxxxx\AppData\Roaming\npm\node_modules\mbexport\build\mbexport'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []

I noticed that it's trying to find the module at C:\Users\xxxxx\AppData\Roaming\npm\node_modules\mbexport\build\mbexport and my directories seem to end at C:\Users\xxxxx\AppData\Roaming\npm\

**Comment by chris-hjelmfelt** [comment]
in your command prompt try typing:
> npm install mbexport

**Comment by chris-hjelmfelt** [comment]
try uninstalling mbexport and then installing it again
> npm uninstall -g mbexport

you could also try forcing an npm update in case npm is having problems
> npm install -g npm@latest --force

**Comment by ReverseControl** [comment]
@Evo-Crypto Did you resolve your issue?

**Comment by armour248** [comment]
@Evo-Crypto Unfortunately I didn't

**Comment by armour248** [comment]
I couldn't figure out my situation either. I just gave up after trying to use mbexport and not getting past the error messages I was getting

**Comment by Evo-Crypto** [comment]
@ReverseControl sadly no. The wallet extractor works quite well for newer wallets I testet with. But with my old Dogecoin wallet it gave an error and asks for my password. Maybe the .wallet file is broken or I forgot my password.

**Comment by ReverseControl** [comment]
If you guys eventually find a solution please post it here. I will suggest we close this issue for the time being.

@patricklodder @rnicoll @michilumin I suggest we close this one.

**Comment by anywalletrecovery** [comment]
I have powerful machine to wallet file of all versions of bitcoin wallet.
I have recovered many bitcoin wallets. and some of the had corrupt file. for fast response text me in telegram or gmail
Telegram: @walletrecover
anywalletrecovery@gmail.com

**Comment by doge2021** [comment]
> i have the same issue, trying to open a old .wallet file errors out with com.google.dogecoin.store.UnreadableWalletException Could not read wallet. i dont have the .info file
do you fixed it? you may reach [BTC recovery service](https://twitter.com/Btc2doge) on twitter. he helped me on my doge wallet year ago. good luck

**Comment by doge2021** [comment]
> I couldn't figure out my situation either. I just gave up after trying to use mbexport and not getting past the error messages I was getting

do you fixed it? you may reach [BTC recovery service](https://twitter.com/Btc2doge) on twitter. he helped me on my doge wallet year ago. good luck

**Comment by doge2021** [comment]
> @ReverseControl sadly no. The wallet extractor works quite well for newer wallets I testet with. But with my old Dogecoin wallet it gave an error and asks for my password. Maybe the .wallet file is broken or I forgot my password.

you need the password to access to it, if you have rough idea of the password, https://www.btc2doge.com/ can help

**Comment by doge2021** [comment]
> I couldn't figure out my situation either. I just gave up after trying to use mbexport and not getting past the error messages I was getting

if you still have the file, can contact https://www.btc2doge.com/ for help

**Comment by bonnelouise** [comment]
I got help from https://cryptorecovers.com amazing service, saw that btc2doge is down. but they did the trick! :)

**Comment by SSouper** [comment]
> I got help from https://cryptorecovers.com amazing service, saw that btc2doge is down. but they did the trick! :)

oh noo did your github account get compromised?
